name: mars_curiosity_app
description: A Mars Curiosity App
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  dio: ^3.0.9
  intl: ^0.16.1
  share: ^0.6.5+4
  screenshot: ^0.3.0
  ars_progress_dialog: ^0.1.2
  path_provider: ^1.6.27
  octo_image: ^0.3.0
  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
